version: '3'
services:


    mosquitto:
        image: eclipse-mosquitto
        volumes:
            - mosquitto-data:/mosquitto/data
            - mosquitto-logs:/mosquitto/logs
            - mosquitto-conf:/mosquitto/config
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto/passwd:/mosquitto/config/passwd
        ports:
            - 1883:1883


    sensor-receptor:
        depends_on:
            - mosquitto
            - postgres
            - redis
        volumes:
            - sensor-receptor:/sensor-receptor/app
        build:
            context: ./sensor-receptor
            dockerfile: ./Dockerfile
        tty: true
        environment:
            MQTT_HOST: mosquitto
            REDIS_HOST: redis
            PGUSER: ctp
            PGHOST: postgres
            PGPASSWORD: secret
            PGDATABASE: iot
            PGPORT: 5432


    redis:
        image: redis
        ports:
            - 6379:6379
    postgres:
        image: postgres
        volumes:
            - ./postgres/gas_volume.sql:/docker-entrypoint-initdb.d/gas_volume.sql
        environment:
            POSTGRES_USER: ctp
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: iot
        ports:
            - 5432:5432


volumes:
    mosquitto-data:
    mosquitto-logs:
    mosquitto-conf:
    sensor-receptor:
