version: '3'
services:

    redis:
        image: redis:6.2
        ports:
            - 6379:6379

    postgres:
        image: postgres:13.4
        volumes:
            - ./postgres/gas_volume_2021_09.sql:/docker-entrypoint-initdb.d/gas_volume_2021_09.sql
        environment:
            POSTGRES_USER: catapult
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: iot
        ports:
            - 5432:5432

    mosquitto:
        image: eclipse-mosquitto:2.0
        volumes:
            - mosquitto-data:/mosquitto/data
            - mosquitto-logs:/mosquitto/logs
            - mosquitto-conf:/mosquitto/config
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto/passwd:/mosquitto/config/passwd
        ports:
            - 1883:1883

    sensor-receptor:
        depends_on:
            - mosquitto
            - postgres
            - redis
        build:
            context: ./sensor-receptor
            dockerfile: ./Dockerfile
        volumes:
            - sensor-receptor:/sensor-receptor/app
        tty: true
        environment:
            MQTT_HOST: mosquitto
            REDIS_HOST: redis
            PGUSER: catapult
            PGHOST: postgres
            PGPASSWORD: secret
            PGDATABASE: iot
            PGPORT: 5432

    api:
        depends_on:
            - postgres
        build:
            context: ./api
            dockerfile: ./Dockerfile
        volumes:
            - api:/api/app
        environment:
            PGUSER: catapult
            PGHOST: postgres
            PGPASSWORD: secret
            PGDATABASE: iot
            PGPORT: 5432
        ports:
            - 4000:4000

    dashboard:
        depends_on:
            - api
        build:
            context: ./dashboard
            dockerfile: ./Dockerfile
        volumes:
            - dashboard:/dashboard/app
        stdin_open: true
        ports:
            - 3000:3000


volumes:
    mosquitto-data:
    mosquitto-logs:
    mosquitto-conf:
    sensor-receptor:
    api:
    dashboard:
